### ISSUE TITLE
Octane guide editions deep dive link is broken

### ISSUE THREAD

**Issue by dineshrbkumar** [ember-learn/guides-source#1297] opened 2020-02-10 06:56 UTC
The deep dive editions [link](https://guides.emberjs.com/release/upgrading/current-edition/editions/) displayed under implementing section of the octane guide  [page](https://guides.emberjs.com/release/upgrading/current-edition) seems to be broken

**Comment by conormag** [comment] 2020-02-10 15:35
this is a duplicate of #1252

**Closed** 2020-02-11 16:50 UTC
Labels: duplicate
