### ISSUE TITLE
Integration Test error @ SuperRentals tutorial - Building Simple Component

### ISSUE THREAD

**Issue by greyhwndz** [ember-learn/guides-source#768] opened 2019-04-26 12:25 UTC

**Comment by greyhwndz** [comment] 2019-04-26 12:28
I have recreated the SuperRentals app by following the recent tutorial and by the time I finished the section on Building Simple Component, the Integration Test failed.

I am attaching the screenshot of the error.

<img width="778" alt="super-rentals-integration-test-error-001" src="https://user-images.githubusercontent.com/13173749/56807555-ca7fcb80-6861-11e9-918a-2ecdd0261566.PNG">

**Comment by jenweber** [comment] 2019-04-26 12:38
Sorry you are having trouble!

- What version of mirage are you using?
- Do you have a JSONAPI serializer for mirage, like here in the sample app? https://github.com/ember-learn/super-rentals/blob/master/mirage/serializers/application.js
- can you push your code up somewhere public?

I’m betting there was a breaking change affecting our examples when mirage did 1.0 this past week.

**Comment by greyhwndz** [comment] 2019-04-26 13:53
@jenweber here is my repo for this
https://github.com/greyhwndz/super-rentals

**Comment by toddjordan** [comment] 2019-04-27 03:51
There is a sample super-rentals repo you can compare to.  Here's what's there.  I see its slightly different than yours. https://github.com/ember-learn/super-rentals/blob/master/tests/integration/components/rental-listing-test.js#L32

I'll run through the tutorial to see if I can reproduce

**Comment by toddjordan** [comment] 2019-04-27 03:53
There looks to be line breaks/whitespace between the "Owner:" and "test-owner" in your impl.  It seems like the problem would be a markup difference in the template issues as opposed to a test issue, but I will look into it and find out for sure.

**Comment by toddjordan** [comment] 2019-04-27 04:33
Alright, walked step by step through the tutorial and the test works for me at the end of building a simple component: 
![image](https://user-images.githubusercontent.com/3609063/56844763-9d441500-6883-11e9-9139-40a16721e8b8.png)

In your repo, notice your component template file around owner
![image](https://user-images.githubusercontent.com/3609063/56844769-d7adb200-6883-11e9-8e6a-a08013a3b941.png)

see how it is different than the tutorial:
![image](https://user-images.githubusercontent.com/3609063/56844775-fad86180-6883-11e9-80db-1d056b1f49e5.png)

You've changed the markup, causing the difference in the assert.

I'm going to go ahead and close the issue.  Thanks for reporting, and continue to let us know as you see problems with the tutorial.

**Closed** 2019-04-27 04:35 UTC

**Comment by greyhwndz** [comment] 2019-04-27 06:40
My VSCode is autoformatting things everytime I save that leads to that. Thanks so much @toddjordan for pointing that out!

**Comment by toddjordan** [comment] 2019-04-28 03:13
hmm.  we could probably create a better assert more tolerant to that.    Might be worth a PR
