### ISSUE TITLE
Generators do not work as described in octane ember-data guide

### ISSUE THREAD

**Issue by john-griffin** [ember-learn/guides-source#956] opened 2019-07-26 00:55 UTC
I hit something when running the first reference to an ember-data generator in the octane docs https://octane-guides-preview.emberjs.com/release/models/defining-models/

https://github.com/john-griffin/guides-source/blame/ac09ffcaa8e9b2a85ff4821427c75ccf0b4c6cf4/guides/release/models/defining-models.md#L12

Running it creates a classic style model. To generate an octane style model the following must run:

`EMBER_VERSION=OCTANE ember generate model person`

How should this be documented?

**Comment by locks** [comment] 2019-09-01 17:49
I can't reproduce it anymore, I'm assuming the issue has been fixed in the latest blueprints :)
Thanks for reporting, and let us know if it happens again for newer versions of the blueprint!

**Closed by locks** 2019-09-01 17:49 UTC
Labels: Octane, help wanted
